name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libglib-2.0-dev libgtk-4-dev libpango1.0-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson setup builddir --prefix=/usr
        meson compile -C builddir
        meson install -C builddir

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: io.elementary.vala-lint -d .
